 If:
   PathMatch: .*\.cpp

CompileFlags:
  Add: [-std=c++23, -Wall, -Wextra]

---

If:
  PathMatch: .*\.c

CompileFlags:
  Add: [
    -xc,
    -std=c17,
    -Werror=missing-braces,
    -DMYLOCAL
  ]
