#!/bin/python3
import click
from fileinput import FileInput
from pathlib import Path


HOME = Path().home()
RUNCACHE_FILE  = HOME/".cache/rofi-4.runcache"
DRUNCACHE_FILE = HOME/".cache/rofi3.druncache"


def reset_cache(line):
    cache = line.split(' ')
    if len(cache) < 2:
        return None
    return '0 ' + ' '.join(cache[1:]).replace('\n', '')


@click.command()
@click.option('--max-size', 'max_size', default=5, type=int, help='Max size of cache to store. Set to -1 to disable.\ndefault: 5')
@click.argument('cache', type=click.Choice(['run', 'drun']))
def main(cache, max_size):
    filename = RUNCACHE_FILE
    if cache == "drun":
        filename = DRUNCACHE_FILE

    lines_printed = 0
    with FileInput(filename, inplace=True, backup='.bak') as f:
        for line in f:
            if lines_printed > max_size:
                break
            new_line = reset_cache(line)
            if new_line is None:
                continue
            print(new_line)
            lines_printed += 1


if __name__ == '__main__':
    main()
